apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-api
spec:
  replicas: 3
  selector:
    matchLabels:
      type: api
      service: go-demo-api
  minReadySeconds: 1
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        type: api
        service: go-demo-api
        language: go
    spec:
      containers:
      - name: api
        image: vinaysaini97/go-mongo-basic
        env:
        - name: DB_HOST
          value: mongo-service
        readinessProbe:
          httpGet:
            path: /hello
            port: 8080
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /hello
            port: 8080