apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness
  labels:
    name: nginx-liveness
spec:
  containers:
  - name: nginx-liveness
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
    livenessProbe:     
      httpGet:        
        path: /       
        port: 80    
      initialDelaySeconds: 5      #          first execution of the probe should bedelayed by five seconds
      timeoutSeconds: 2 # Defaults to 1      requests shouldtimeout after two seconds
      periodSeconds: 5 # Defaults to 10      process should be repeated every period seconds
      failureThreshold: 1 # Defaults to 3    how many attempts it must try before giving up
