apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: go-mongo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-mongo-app
  template:
    metadata:
      name: go-mongo-app
      labels:
        app: go-mongo-app
    spec:
      containers:
        - name: go-mongo-app
          image: vinaysaini97/go-mongo-basic
          ports:
            - containerPort: 8080
          env:
          - name: DB_HOST
            value: mongo-service
