apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      name: mongo-db
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-db
          image: mongo
          ports:
            - containerPort: 28017
